package projet_java;

public enum EnumMimeType {

	 
	/**
	 * Les différents Mime-Type (couple extension/content type).
	 * L'extension sans le point.
	 * TODO A COMPLETER
	 * @author Thomas Noirez
	 *
	 */
		_123 ("application/vnd.lotus-1-2-3"),
		_3dm ("x-world/x-3dmf"),
		_3dmf ("x-world/x-3dmf"),
		_3gp ("video/3gp"),
		_3gpp ("audio/3gp"),
		aab ("application/x-authorware-bin"),
		aam ("application/x-authorware-map"),
		aas ("application/x-authorware-map"),
		adr ("application/x-msaddr"),
		afl ("video/animaflex"),
		ai ("application/postscript"),
		aif ("audio/x-aiff"),
		aifc ("audio/x-aiff"),
		aiff ("audio/x-aiff"),
		alt ("application/x-up-alert"),
		aos ("application/x-nokia-9000-communicator-add-on-software"),
		arj ("application/x-arj"),
		asc ("text/plain"),
		asd ("application/astound"),
		asf ("video/x-ms-asf"),
		asn ("application/astound"),
		asp ("application/x-asap"),
		asx ("video/x-ms-asf"),
		asz ("application/astound"),
		au ("audio/basic"),
		avi ("video/avi"),
		axs ("application/olescript"),
		bas ("text/plain"),
		bat ("text/plain"),
		bcpio ("application/x-bcpio"),
		bin ("application/octet-stream"),
		bmp ("image/bmp"),
		cacert ("application/x-x509-ca-cert"),
		ccs ("text/ccs"),
		cdf ("application/x-netcdf"),
		cdr ("application/x-cdr"),
		cer ("application/x-x509-ca-cert"),
		chat ("application/x-chat"),
		che ("application/x-up-cacheop"),
		cht ("audio/x-dspeech"),
		_class ("application/octet-stream"),
		clp ("image/x-clp"),
		cmd ("text/plain"),
		cmx ("image/x-cmx"),
		cnc ("application/x-cnc"),
		cod ("image/cis-cod"),
		coda ("application/x-coda"),
		com ("application/octet-stream"),
		con ("application/x-connector"),
		cpi ("image/cpi"),
		cpio ("application/x-cpio"),
		csh ("application/x-csh"),
		csm ("application/x-cu-seeme"),
		css ("text/css"),
		csv ("text/comma-separated-values"),
		cu ("application/x-cu-seeme"),
		cut ("image/x-halo-cut"),
		dbf ("application/octet-stream"),
		dcr ("application/x-director"),
		dig ("multipart/mixed"),
		dir ("application/x-director"),
		doc ("application/msword"),
		dsf ("image/x-mgx-dsf"),
		dss ("text/dss"),
		dst ("application/tajima"),
		dus ("audio/x-dspeech"),
		dvi ("application/x-dvi"),
		dwf ("drawing/x-dwf"),
		dwg ("image/vnd"),
		dxf ("image/vnd"),
		dxr ("application/x-director"),
		ebk ("application/x-expandedbook"),
		ecert ("application/x-x509-email-cert"),
		email ("application/x-x509-email-cert"),
		emf ("image/x-emf"),
		eps ("application/postscript"),
		erf ("application/x-hsp-erf"),
		es ("audio/echospeech"),
		etf ("image/x-etf"),
		etx ("text/x-setext"),
		evy ("application/envoy"),
		exe ("application/x-msdownload"),
		fh4 ("image/x-freehand"),
		fh5 ("image/x-freehand"),
		fhc ("image/x-freehand"),
		fif ("image/fif"),
		fml ("application/fml"),
		fpx ("image/x-fpx"),
		frl ("application/freeloader"),
		fs ("application/X-FSRecipe"),
		gif ("image/gif"),
		gsd ("audio/gsm"),
		gsm ("audio/gsm"),
		gtar ("application/x-gtar"),
		gvi ("?"),
		gvp ("?"),
		gz ("application/gzip"),
		hdf ("application/x-hdf"),
		hdml ("text/x-hdml"),
		hqx ("application/mac-binhex40"),
		htm ("text/html"),
		html ("text/html"),
		ica ("application/x-ica"),
		ief ("image/ief"),
		ins ("application/x-NET-Install"),
		ips ("application/ips"),
		ipx ("application/x-ipix"),
		ivr ("i-world/i-vrml"),
		jad ("text/vnd.sun.j2me.app-descriptor"),
		jar ("application/java-archive"),
		jardiff ("application/x-java-archive-diff"),
		java ("text/x-java-source"),
		jnlp ("application/x-java-jnlp-file"),
		jp2 ("image/jp2"),
		jpe ("image/jpeg"),
		jpeg ("image/jpeg"),
		jpg ("image/jpeg"),
		jps ("image/x-jps"),
		js ("application/x-javascript"),
		latex ("application/x-latex"),
		lha ("application/octet-stream"),
		lit("application/lit"),
		log("text/plain"),
		lsp ("text/lsp"),
		lwp ("application/x-wordpro"),
		lzh ("application/octet-stream"),
		lzx ("application/octet-stream"),
		m3u ("audio/x-mpegurl"),
		man ("application/x-troff-man"),
		map ("application/x-httpd-imap"),
		mbd ("application/mbedlet"),
		mcf ("image/vasa"),
		mdb ("application/mdb"),
		me ("application/x-troff-me"),
		mfp ("application/mirage"),
		mid ("audio/x-midi"),
		midi ("audio/x-midi"),
		mif ("application/x-mif"),
		mol ("chemical/x-mdl-molfile"),
		mov ("video/quicktime"),
		movie ("video/x-sgi-movie"),
		mp2 ("audio/x-mpeg"),
		mp3 ("audio/mpeg"),
		mpe ("video/mpeg"),
		mpeg ("video/mpeg"),
		mpg ("video/mpeg"),
		mpire ("application/x-mpire"),
		mpl ("application/x-mpire"),
		mpp ("application/vnd.ms-project"),
		ms ("application/x-troff-ms"),
		msi ("application/msi"),
		msm ("application/msm"),
		n2p ("application/n2p"),
		nc ("application/x-netcdf"),
		npx ("application/x-netfpx"),
		nsc ("application/x-nschat"),
		oda ("application/oda"),
		ofml ("application/fml"),
		page ("application/x-coda"),
		pbd ("application/vnd.powerbuilder6"),
		pbm ("image/x-portable-bitmap"),
		pdb ("chemical/x-pdb"),
		pdf ("application/pdf"),
		pfr ("application/font-tdpfr"),
		pgm ("image/x-portable-graymap"),
		pgp ("application/x-pgp-plugin"),
		pgr ("text/parsnegar-document"),
		php ("application/x-httpd-php"),
		php3 ("application/x-httpd-php3"),
		php4 ("application/x-httpd-php"),
		pls ("application/pls"),
		png ("image/png"),
		pnm ("image/x-portable-anymap"),
		pot ("application/mspowerpoint"),
		ppm ("image/x-portable-pixmap"),
		pps ("application/mspowerpoint"),
		ppt ("application/mspowerpoint"),
		ppz ("application/mspowerpoint"),
		pqf ("application/x-cprplayer"),
		pqi ("application/cprplayer"),
		ps ("application/postscript"),
		psr ("application/datawindow"),
		ptlk ("application/listenup"),
		push ("multipart/x-mixed-replace"),
		qd3 ("x-world/x-3dmf"),
		qd3d ("x-world/x-3dmf"),
		qrt ("application/quest"),
		qt ("video/quicktime"),
		qti ("image/x-quicktime"),
		qtl ("application/x-quicktimeplayer"),
		ra ("audio/x-pn-realaudio"),
		ram ("audio/x-pn-realaudio"),
		ras ("image/x-cmu-raster"),
		rgb ("image/x-rgb"),
		rip ("image/rip"),
		rm ("audio/x-pn-realaudio"),
		rmf ("audio/rmf"),
		rng ("application/ringing-tones"),
		roff ("application/x-troff"),
		rpm ("audio/x-pn-realaudio-plugin"),
		rrf ("application/x-InstallFromTheWeb"),
		rss ("application/rss+xml"),
		rtc ("application/rtc"),
		rtf ("application/rtf"),
		rtx ("text/richtext"),
		sca ("application/x-supercard"),
		scert ("application/x-x509-server-cert"),
		scr ("application/octet-stream"),
		seq ("application/octet-stream-bin"),
		ser ("application/x-java-serialized-object"),
		sh ("application/x-sh"),
		shar ("application/x-shar"),
		shtml ("text/x-server-parsed-html"),
		shw ("application/presentations"),
		sit ("application/x-stuffit"),
		sjf ("application/octet-stream"),
		smi ("application/smil"),
		smil ("application/smil"),
		sml ("application/smil"),
		smp ("application/studiom"),
		snd ("audio/basic"),
		spc ("text/x-speech"),
		spl ("application/futuresplash"),
		spr ("application/x-sprite"),
		sprite ("application/x-sprite"),
		sql ("text/plain"),
		src ("application/x-wais-source"),
		ssi ("text/x-server-parsed-html"),
		stk ("application/hstu"),
		stream ("audio/x-qt-stream"),
		sv4cpio ("application/x-sv4cpio"),
		sv4crc ("application/x-sv4crc"),
		svf ("image/vnd"),
		svh ("image/svh"),
		svr ("x-world/x-svr"),
		swa ("application/x-director"),
		swf ("application/x-shockwave-flash"),
		t ("application/x-troff"),
		talk ("application/talker"),
		tar ("application/x-tar"),
		tbk ("application/toolbook"),
		tcl ("application/x-tcl"),
		tex ("application/x-tex"),
		texi ("application/x-texinfo"),
		texinfo ("application/x-texinfo"),
		text ("text/plain"),
		tgz ("application/gzip"),
		tif ("image/tiff"),
		tiff ("image/tiff"),
		tlk ("application/x-tlk"),
		tmv ("application/x-Parable-Thing"),
		torrent ("application/x-bittorrent"),
		tr ("application/x-troff"),
		troff ("application/x-troff"),
		tsi ("audio/tsplayer"),
		tsp ("application/dsptype"),
		tsq ("application/timestamp-query"),
		tsr ("application/timestamp-reply"),
		tsv ("text/tab-separated-values"),
		txt ("text/plain"),
		u98 ("urdu/urdu98"),
		ucert ("application/x-x509-user-cert"),
		uin ("application/x-icq"),
		usercert ("application/x-x509-user-cert"),
		usr ("application/x-x509-user-cert"),
		ustar ("application/x-ustar"),
		vbd ("application/activexdocument"),
		vcd ("application/x-cdlink"),
		vcf ("text/x-vcard"),
		vew ("application/groupwise"),
		vgm ("video/x-videogram"),
		vgp ("video/x-videogram-plugin"),
		vgx ("video/x-videogram"),
		viv ("video/vnd.vivo"),
		vivo ("video/vnd.vivo"),
		vmd ("application/vocaltec-media-desc"),
		vmf ("application/vocaltec-media-file"),
		vmi ("application/x-dreamcast-vms-info"),
		vms ("application/x-dreamcast-vms"),
		vox ("audio/voxware"),
		vpa ("application/vpa"),
		vqe ("audio/x-twinvq-plugin"),
		vqf ("audio/x-twinvq"),
		vql ("audio/x-twinvq"),
		vrt ("x-world/x-vrt"),
		vts ("workbook/formulaone"),
		vtts ("workbook/formulaone"),
		w60 ("application/wordperfect6.0"),
		w61 ("application/wordperfect6.1"),
		waf ("plugin/wanimate"),
		wan ("plugin/wanimate"),
		wav ("audio/wav"),
		wax ("audio/x-ms-wax"),
		wbmp ("image/vnd.wap.wbmp"),
		wi ("image/wavelet"),
		wid ("application/x-DemoShield"),
		wis ("application/x-InstallShield"),
		wlt ("application/x-mswallet"),
		wm ("video/x-ms-wm"),
		wma ("audio/x-ms-wma"),
		wmd ("application/x-ms-wmd"),
		wmf ("image/x-wmf"),
		wml ("x-world/x-vrml"),
		wmlc ("application/vnd.wap.wmlc"),
		wmls ("text/vnd.wap.wmlscript"),
		wmlsc ("application/vnd.wap.wmlscriptc"),
		wmv ("video/x-ms-wmv"),
		wmx ("video/x-ms-wmx"),
		wmz ("application/x-ms-wmz"),
		wp ("application/wordperfect"),
		wp5 ("application/wordperfect"),
		wpd ("application/wordperfect5.1"),
		wri ("application/write"),
		wrl ("x-world/x-vrml"),
		wrz ("x-world/x-vrml"),
		wtx ("audio/wtx"),
		wvx ("video/x-ms-wvx"),
		xbm ("image/x-xbitmap"),
		xdr ("video/x-videogram"),
		xif ("image/vnd.xiff"),
		xla ("application/vnd.ms-excel"),
		xlc ("application/vnd.ms-excel"),
		xlm ("application/vnd.ms-excel"),
		xls ("application/vnd.ms-excel"),
		xlt ("application/vnd.ms-excel"),
		xlw ("application/vnd.ms-excel"),
		xml ("application/xml"),
//		xls  application/vnd.ms-excel
//		xhtml
		xpm ("image/x-xpixmap"),
		xwd ("image/x-xwindowdump"),
		
		z ("application/x-compress"),
//		zip ("application/x-zip-compressed"),
		zip("application/zip"),
		
		zpa ("application/pcphoto"),
		flv	("video/x-flv"),
		mp4	("video/mp4"),
		m3u8	("application/x-mpegURL"),
		ts	("video/MP2T"),
		UNKNOWN ("text/unknown");
	 	
	
		
		private String _value;
	 
		/**
	         * @param value
	         */
	
		EnumMimeType(String value) {
			_value = value;
		}
	 
		/**
	         * @return the value
	         */
		public final String getValue() 
		{
			return _value;
		}
	
}


